### ISSUE TITLE
Importing full zip doesn't work for WinTak but importing individual .XMLs does seem to work. 

### ISSUE THREAD

**Issue by sntrenter** [joshuafuller/ATAK-Maps#16]
Might want to note that in the instructions and possibly create a release that groups them all in one folder to be imported at once.

**Comment by joshuafuller** [comment]
Thanks for the heads up @sntrenter . I updated the much over due instructions with commit: 1b57d2ee8448d4f815674f6b0ef7c8b823c883b8
