### ISSUE TITLE
Maps not working for me!!

### ISSUE THREAD

**Issue by atSurvival** [joshuafuller/ATAK-Maps#17]
I use ATAK Civ since release (first Google Drive Download and later from the AppStore ) and also your map.zip.
Today I reinstalled the app and Imported the map.zip but the Maps doesn't appear in the app.
I tried it with the Import Manager and the Data package Funktion. Nothing.
I deleteD all ATAK files what I could found. Reinstalled. Nothing.
I hope someone have an idea to fix this.

Regards
Survival

**Comment by khanfar** [comment]
Im. Just download the civil version from play store, when i try locate my gps location, no map appears just blank. The map you try install its worldwide?

**Comment by chandcoc** [comment]
Same issue here. Never used the app (or map pack) till now, but can "import" the zip file, but nothing shows up map wise.

**Comment by atSurvival** [comment]
I have had the same issue. Extract the map.zip and drag it manually in the
destination folder. It worked for me.

**Comment by chandcoc** [comment]
Was in the process of trying that actually.... And worked here too for the ones I was interested in. Just extracted the zip, and added the .XML files to the imagery folder


<https://aka.ms/AAb9ysg>
________________________________

**Comment by joshuafuller** [comment]
I've updated the README's instructions to try to clarify the method in recent ATAK updates. Please let me know if I missed anything.

See commit: 1b57d2ee8448d4f815674f6b0ef7c8b823c883b8

**Comment by PeterSprague** [comment]
I have the developer version of TAK/ATAK-CIV installed on an older Samsung tablet.

Imported the complete ATAK-MAPS.zip from my Downloads folder on the SD card.  Everything except OSM maps works great, caches, etc.  I tried to follow the revised directions to unzip and import each folder or XML file.  TAK errored with that method.
