### ISSUE TITLE
OGC WMS and OGC WMTS mapping service URL's?

### ISSUE THREAD

**Issue by geospatialmapmashup** [joshuafuller/ATAK-Maps#9]
In the Discord or Reddit some users mentioned support for OGC WMS and OGC WMTS
do you have any information about adding those URL's?

What about TMS instead of XYZ  Tile Servers?
is there a flag or parameter for denoting Flipping the Y Row like -y or reverseY?

**Comment by joshuafuller** [comment]
These files are MOBAC compatible XMLs. I would have to refer to the MOBAC documentation.
